[settings]
require_version = "2.0.0"
include_os_env = true
print_env = true
print_parsed = false
print_successful = true

[env]
DOWNLOAD = "C:/Users/alex/Downloads"
SCREENSHOTS = "C:/Users/alex/Pictures/Screenshots"
RECURSIVE = "${DOWNLOAD}"

[embed]
"test.hpp" = ["${RECURSIVE}/pfpcrussy.png", "${SCREENSHOTS}/normalize.png"]

