if(NOT WIN32 OR $ENV{CLION_IDE})
    string(ASCII 27 Esc)
    set(ColReset    "${Esc}[m")
    set(ColBold     "${Esc}[1m")
    set(Red         "${Esc}[31m")
    set(Green       "${Esc}[32m")
    set(Yellow      "${Esc}[33m")
    set(Blue        "${Esc}[34m")
    set(Magenta     "${Esc}[35m")
    set(Cyan        "${Esc}[36m")
    set(White       "${Esc}[37m")
    set(BoldRed     "${Esc}[1;31m")
    set(BoldGreen   "${Esc}[1;32m")
    set(BoldYellow  "${Esc}[1;33m")
    set(BoldBlue    "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan    "${Esc}[1;36m")
    set(BoldWhite   "${Esc}[1;37m")
else()
    string(ASCII 27 Esc)
    set(ColReset    "")
    set(ColBold     "")
    set(Red         "")
    set(Green       "")
    set(Yellow      "")
    set(Blue        "")
    set(Magenta     "")
    set(Cyan        "")
    set(White       "")
    set(BoldRed     "")
    set(BoldGreen   "")
    set(BoldYellow  "")
    set(BoldBlue    "")
    set(BoldMagenta "")
    set(BoldCyan    "")
    set(BoldWhite   "")
endif()

function(cmessage)
    list(GET ARGV 0 MessageType)
    if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR OR MessageType STREQUAL WARNING)
        list(REMOVE_AT ARGV 0)
        message(${MessageType} "${ARGV}")
    elseif(MessageType STREQUAL AUTHOR_WARNING OR MessageType STREQUAL STATUS)
        list(REMOVE_AT ARGV 0)
        message(${MessageType} "${ARGV}")
    elseif(MessageType STREQUAL LIGHT_WARNING)
        list(REMOVE_AT ARGV 0)
        message("${Red}${ARGV}${ColReset}")
    elseif(MessageType STREQUAL NOTICE_YELLOW)
        list (REMOVE_AT ARGV 0)
        message("${Yellow}${ARGV}${ColReset}")
    elseif(MessageType STREQUAL NOTICE_GREEN)
        list (REMOVE_AT ARGV 0)
        message("${Green}${ARGV}${ColReset}")
    elseif(MessageType STREQUAL NOTICE_BLUE)
        list (REMOVE_AT ARGV 0)
        message("${Blue}${ARGV}${ColReset}")
    elseif(MessageType STREQUAL NOTICE_PURPLE)
        list (REMOVE_AT ARGV 0)
        message("${Magenta}${ARGV}${ColReset}")
    else()
        _message("${ARGV}")
    endif()
endfunction()